FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir \
    streamlit \
    boto3 \
    python-dotenv

EXPOSE 8501

CMD ["streamlit", "run", "src/dreamsculpt_be/view_user_logs.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true"]
